trigger:
  - master

variables:
  vmImageName: ubuntu-latest

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: "build"
          - task: DotNetCoreCLI@2
            displayName: Tests
            inputs:
              command: 'test'
              arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
              publishTestResults: true
          - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
            displayName: Merge
            inputs:
              reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
              targetdir: '$(Pipeline.Workspace)/coverlet'
              reporttypes: 'Cobertura'
              verbosity: 'Verbose'
          - task: PublishCodeCoverageResults@1
            displayName: CodeCoverage
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(Pipeline.Workspace)/coverlet/Cobertura.xml'