trigger:
  - master

variables:
  vmImageName: ubuntu-latest

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: "build"
          - task: DotNetCoreCLI@2
            displayName: Tests
            inputs:
              command: 'test'
              arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
              publishTestResults: true
          - task: DotNetCoreCLI@2
            displayName: Execução dos Testes de Unidade
            inputs:
              command: 'test'
              projects: '$(pathToTestProject)'
              arguments: '--configuration $(buildConfiguration) --collect "XPlat Code coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
              publishTestResults: true
          - task: PublishCodeCoverageResults@1
            displayName: CodeCoverage
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'