trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: "build"
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'